version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: saikrishna
      MONGO_INITDB_ROOT_PASSWORD: saikrishna488
      MONGO_INITDB_DATABASE: bangaram
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: .
    container_name: node-app
    environment:
      MONGO_URI: mongodb://saikrishna:saikrishna488@mongo-db:27017/bangaram?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/usr/src/app

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: