version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: node-app
    environment:
      MONGO_URI: mongodb://mongo-db:27017/bangaram
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

volumes:
  mongo_data:
